### ISSUE TITLE
Доработка

### ISSUE THREAD

**Issue by TonitaN** [boomb0om/FormalLanguageTheory#1]
1. В случае неудачи унификации вывод должен идти в стандартный поток, а не в поток ошибок. При этом должна быть описана ситуация неудачи (где найден цикл или какие конструкторы не удалось унифицировать)
2. Нужно корректно обрабатывать пробелы и лишние переводы строки в парсере.
3. Иногда объявляется о цикле в унификации, хотя его нет [UnificError.txt](https://github.com/boomb0om/FormalLanguageTheory/files/9710374/UnificError.txt). Исправить.
4. Дисбаланс скобок нужно определять, а не списывать на неизвестный терм. Больше того, необходимо определять первую лишнюю открывающую скобку, либо позицию первой лишней закрывающей скобки.
5. Местность конструкторов должна соответствовать сигнатуре (если в сигнатуре указано 3 аргумента, то везде должно быть 3). 
6. В итоговый терм-результат унификации нужно сделать все подстановки.

**Comment by megamax625** [comment]
залил сюда: https://github.com/megamax625/FormalLanguageTheory
