### ISSUE TITLE
Некорректная обработка входных данных для ГНФ

### ISSUE THREAD

**Issue by pollykon** [boomb0om/FormalLanguageTheory#2]
[S]->[X][A]
[S]->[B][B]
[B]->b
[B]->[S][B]
[X]->b
[A]->a

Это пример с нормальным вводом. Но если вдруг для какого-то нетерминала не будет вообще правил (например уберем для [A]), то в ходе программы выскочит ошибка KeyError. А по идее должно выводиться предупреждение что ввод некорректен. 

[S]->[X][A]
[S]->[B][B]
[B]->b
[B]->[S][B]
[X]->b

**Comment by boomb0om** [comment]
Исправлено
